import enum
from typing import Any, Dict
from pydantic import BaseModel


class WSEventType(str, enum.Enum):
    NEW_ORDER = "NEW_ORDER"
    ORDER_STATUS_CHANGED = "ORDER_STATUS_CHANGED"
    KITCHEN_ALERT = "KITCHEN_ALERT"
    CUSTOMER_REQUEST = "CUSTOMER_REQUEST"
    REQUEST_STATUS_CHANGED = "REQUEST_STATUS_CHANGED"
    REQUEST_ACCEPTED = "REQUEST_ACCEPTED"
    REQUEST_IN_PROGRESS = "REQUEST_IN_PROGRESS"
    REQUEST_COMPLETED = "REQUEST_COMPLETED"
    MENU_UPDATED = "MENU_UPDATED"
    TABLE_UPDATED = "TABLE_UPDATED"
    SESSION_STARTED = "SESSION_STARTED"
    SESSION_UPDATED = "SESSION_UPDATED"
    SESSION_CLOSED = "SESSION_CLOSED"
    EMPLOYEE_ONLINE = "EMPLOYEE_ONLINE"
    EMPLOYEE_OFFLINE = "EMPLOYEE_OFFLINE"
    EMPLOYEE_STATUS_CHANGED = "EMPLOYEE_STATUS_CHANGED"
    EMPLOYEE_UPDATED = "EMPLOYEE_UPDATED"


class WSEventPayload(BaseModel):
    event_type: WSEventType
    restaurant_id: str
    data: Dict[str, Any]
